language: cpp

os:
  - linux
  - osx

dist: xenial

env:
  matrix:
    - libt_branch=RC_1_1 gui=true build_system=qmake
    - libt_branch=RC_1_1 gui=false build_system=qmake
    - libt_branch=RC_1_1 gui=true build_system=cmake
    - libt_branch=RC_1_1 gui=false build_system=cmake
    - libt_branch=RC_1_2 gui=true build_system=qmake
  global:
    - secure: "OI9CUjj4lTb0HwwIZU5PbECU3hLlAL6KC8KsbwohG8/O3j5fLcnmDsK4Ad9us5cC39sS11Jcd1kDP2qRcCuST/glVNhLkcjKkiQerOfd5nQ/qL4JYfz/1mfP5mdpz9jHKzpLUIG+TXkbSTjP6VVmsb5KPT+3pKEdRFZB+Pu9+J8="
    - coverity_branch: coverity_scan

matrix:
  allow_failures:
    - env: libt_branch=RC_1_1 gui=true build_system=cmake
    - env: libt_branch=RC_1_1 gui=false build_system=cmake
    - env: libt_branch=RC_1_2 gui=true build_system=qmake

branches:
  except:
    - search_encoding_windows
    - v2_9_x

notifications:
  email:
    on_success: change
    on_failure: change

cache:
  ccache: true
  directories:
    - $HOME/hombebrew_cache

addons:
  coverity_scan:
    project:
      name: "qbittorrent/qBittorrent"
      description: "Build submitted via Travis CI"
    build_command_prepend: "./bootstrap.sh && ./configure $qmake_conf"
    build_command: make
    branch_pattern: $coverity_branch
    notification_email: sledgehammer999@qbittorrent.org
  apt:
    sources:
      # sources list: https://github.com/travis-ci/apt-source-safelist/blob/master/ubuntu.json
      - sourceline: 'ppa:qbittorrent-team/qbittorrent-stable'
    packages:
      # packages list: https://github.com/travis-ci/apt-package-safelist/blob/master/ubuntu-trusty
      - [autoconf, automake, colormake]
      - [libboost-dev, libboost-system-dev]
      - libssl-dev
      - libtorrent-rasterbar-dev
      - [qtbase5-dev, qttools5-dev-tools, libqt5svg5-dev]
      - zlib1g-dev
  homebrew:
    update: true
    packages:
      - [ccache, colormake]
      - boost
      - libtorrent-rasterbar
      - openssl
      - qt
      - zlib

before_install:
  # only allow specific build for coverity scan, others will stop
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ] && ! [ "$TRAVIS_OS_NAME" = "linux" -a "$libt_branch" = "RC_1_1" -a "$gui" = "true" -a "$build_system" = "qmake" ]; then exit ; fi

  - shopt -s expand_aliases
  - alias make="colormake -j2" # Using nprocs/2 sometimes may fail (gcc is killed by system)
  - qbt_path="$HOME/qbt_install"
  - qmake_conf="$qmake_conf --prefix=$qbt_path"
  - cmake_conf="$cmake_conf -DCMAKE_INSTALL_PREFIX=$qbt_path"

  # options for specific branches
  - |
    if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      # setup virtual display for after_success target
      if [ "$gui" = "true" ]; then export "DISPLAY=:99.0" && /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 ; fi ;
    fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      CXXFLAGS="$CXXFLAGS -Wno-unused-local-typedefs -Wno-inconsistent-missing-override"

      openssl_root_path="/usr/local/opt/openssl"
      qmake_conf="$qmake_conf PKG_CONFIG_PATH=$openssl_root_path/lib/pkgconfig:$PKG_CONFIG_PATH"
      cmake_conf="$cmake_conf -DOPENSSL_ROOT_DIR=$openssl_root_path"
    fi
  - |
    if [ "$gui" = "false" ]; then
      qmake_conf="$qmake_conf --disable-gui"
      cmake_conf="$cmake_conf -DCMAKE_DISABLE_FIND_PACKAGE_Qt5Widgets=ON"
    fi

  # print settings
  - echo $libt_branch
  - echo $gui
  - echo $build_system
  - echo $qmake_conf
  - echo $cmake_conf

install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      # dependencies
      PATH="/usr/local/opt/ccache/libexec:$PATH"

      brew outdated cmake || brew upgrade cmake
      brew outdated pkg-config || brew upgrade pkg-config
      brew link --force qt zlib

      if [ "$build_system" = "cmake" ]; then
        sudo ln -s /usr/local/opt/qt/mkspecs /usr/local/mkspecs
        sudo ln -s /usr/local/opt/qt/plugins /usr/local/plugins
      fi
    fi
  - |
    if [ "$TRAVIS_BRANCH" != "$coverity_branch" ]; then
      export use_ccache=true
      ccache -M 512M
      ccache -V && ccache --show-stats && ccache --zero-stats
    fi
  - |
    # build libtorrent from source
    if [ "$libt_branch" = "RC_1_2" ]; then
      cd "$HOME"
      git clone --depth 1 https://github.com/arvidn/libtorrent.git --branch $libt_branch
      cd libtorrent && mkdir _build && cd _build
      CXXFLAGS="$CXXFLAGS -std=c++14" cmake -Ddeprecated-functions=OFF -DOPENSSL_ROOT_DIR="$openssl_root_path" ../
      make && sudo make install
    fi

script:
  - if [ "$TRAVIS_BRANCH" = "$coverity_branch" ]; then exit ; fi # skip usual build when running coverity scan
  - |
    cd "$TRAVIS_BUILD_DIR"
    if [ "$build_system" = "qmake" ]; then
      ./bootstrap.sh
      ./configure $qmake_conf CXXFLAGS="$CXXFLAGS"
    else
      mkdir build && cd build
      cmake $cmake_conf ../
    fi
  - make && make install

after_success:
  - if [ "$gui" = "true" ]; then qbt_exe="qbittorrent" ; else qbt_exe="qbittorrent-nox" ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cd "$qbt_path/bin" ; fi
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      if [ "$build_system" = "qmake" ]; then
        macdeployqt "$TRAVIS_BUILD_DIR/src/$qbt_exe.app"
        cd "$TRAVIS_BUILD_DIR/src/$qbt_exe.app/Contents/MacOS"
      else
        cd "$qbt_path/$qbt_exe.app/Contents/MacOS"
      fi
    fi
  - ./$qbt_exe --version

after_script:
  - if [ "$use_ccache" = true ]; then ccache --show-stats ; fi
